---
- name: "pull images and start docker compose"
  hosts: localhost
  tasks:
    - name: "Pull docker images"
      command: "docker-compose -f docker-compose.yml pull"
    - name: "Start docker compose"
      command: "docker-compose -f docker-compose.yml up -d"